title: ej-cafe
title_separator: "-"
name: EJ-Cafe
description: Judy和Evan的咖啡屋。
minimal_mistakes_skin: dark
theme: jekyll-theme-midnight
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-avatar
  - jemoji
  - jekyll-mentions
  - jekyll-include-cache
  - jekyll-paginate